global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'pixelpet'
    static_configs:
      - targets: ['pixelpet:8080']
